-- Inserir todos os flashcards do Cegalla
INSERT INTO flashcards (topic_id, question, answer) VALUES
('fonetica-fonologia', 'O que é um fonema?', 'Menor unidade sonora da fala que distingue significados.'),
('fonetica-fonologia', 'O que é um ditongo?', 'Encontro de duas vogais em uma mesma sílaba.'),
('fonetica-fonologia', 'O que é um hiato?', 'Encontro de duas vogais em sílabas diferentes.'),
('fonetica-fonologia', 'O que é um tritongo?', 'Encontro de três vogais em uma mesma sílaba.'),
('fonetica-fonologia', 'O que é um dígrafo?', 'Duas letras que representam um único som.'),
('fonetica-fonologia', 'O que é um encontro consonantal?', 'Sequência de duas ou mais consoantes sem vogal intermediária.'),
('fonetica-fonologia', 'Como se faz a divisão silábica de ''psicologia''?', 'psi-co-lo-gi-a'),
('fonetica-fonologia', 'O que é uma vogal?', 'Som produzido sem obstrução do ar na boca.'),
('fonetica-fonologia', 'O que é uma semivogal?', 'Vogal com som mais fraco, acompanhando outra vogal.'),
('fonetica-fonologia', 'O que é uma consoante?', 'Som produzido com obstrução do ar na boca.'),
('fonetica-fonologia', 'Exemplo de ditongo crescente.', 'Quase (qua-se)'),
('fonetica-fonologia', 'Exemplo de ditongo decrescente.', 'Pai (pai)'),
('fonetica-fonologia', 'Exemplo de hiato.', 'Saída (sa-í-da)'),
('fonetica-fonologia', 'Exemplo de tritongo.', 'Paraguai (Pa-ra-guai)'),
('fonetica-fonologia', 'Exemplo de dígrafo.', 'Chuva (ch)'),
('fonetica-fonologia', 'Exemplo de encontro consonantal perfeito.', 'Planta (pl)'),
('fonetica-fonologia', 'Exemplo de encontro consonantal imperfeito.', 'Ritmo (tm)'),
('fonetica-fonologia', 'O que é sílaba tônica?', 'Sílaba mais forte da palavra.'),
('fonetica-fonologia', 'O que é sílaba átona?', 'Sílaba fraca da palavra.'),
('fonetica-fonologia', 'O que é um acento tônico?', 'Intensidade sonora da sílaba.'),
('fonetica-fonologia', 'O que é um acento gráfico?', 'Sinal que indica a sílaba tônica.'),
('fonetica-fonologia', 'O que é um monossílabo?', 'Palavra com uma única sílaba.'),
('fonetica-fonologia', 'O que é um dissílabo?', 'Palavra com duas sílabas.'),
('fonetica-fonologia', 'O que é um trissílabo?', 'Palavra com três sílabas.'),
('fonetica-fonologia', 'O que é um polissílabo?', 'Palavra com quatro ou mais sílabas.'),
('fonetica-fonologia', 'O que é um fonema vocálico?', 'Fonema que corresponde a uma vogal.'),
('fonetica-fonologia', 'O que é um fonema consonantal?', 'Fonema que corresponde a uma consoante.'),
('fonetica-fonologia', 'O que é um fonema semivocálico?', 'Fonema que corresponde a uma semivogal.'),
('fonetica-fonologia', 'O que é um som nasal?', 'Som produzido com o ar saindo pelo nariz.'),
('fonetica-fonologia', 'O que é um som oral?', 'Som produzido com o ar saindo pela boca.'),
('ortografia', 'Qual a diferença entre ''mas'' e ''mais''?', '''Mas'' é conjunção adversativa; ''mais'' é advérbio de intensidade.'),
('ortografia', 'Quando usar ''por que'' separado e sem acento?', 'Em perguntas diretas ou indiretas, ou quando ''que'' é pronome relativo.'),
('ortografia', 'Quando usar ''porquê'' junto e com acento?', 'Quando é substantivo, geralmente precedido de artigo.'),
('ortografia', 'Qual a regra para o uso do hífen em ''bem-vindo''?', 'Com prefixos ''bem'' e ''mal'' seguidos de vogal ou ''h''.'),
('ortografia', 'Quando usar ''sessão'', ''seção'' e ''cessão''?', '''Sessão'' (tempo de reunião), ''seção'' (divisão), ''cessão'' (ato de ceder).'),
('ortografia', 'Qual a diferença entre ''onde'' e ''aonde''?', '''Onde'' indica lugar fixo; ''aonde'' indica movimento.'),
('ortografia', 'Quando usar ''há'' e ''a'' (tempo)?', '''Há'' (verbo haver) indica tempo passado; ''a'' indica tempo futuro ou distância.'),
('ortografia', 'Qual a diferença entre ''senão'' e ''se não''?', '''Senão'' (caso contrário, a não ser); ''se não'' (conjunção ''se'' + advérbio ''não'').'),
('ortografia', 'Quando usar ''mau'' e ''mal''?', '''Mau'' é adjetivo (oposto de bom); ''mal'' é advérbio (oposto de bem).'),
('ortografia', 'Qual a diferença entre ''traz'' e ''trás''?', '''Traz'' (verbo trazer); ''trás'' (advérbio de lugar).'),
('acentuacao-grafica', 'Quando acentuar oxítonas?', 'Terminadas em A(s), E(s), O(s), EM, ENS.'),
('acentuacao-grafica', 'Quando acentuar paroxítonas?', 'Quando não terminam em A(s), E(s), O(s), EM, ENS, e outras regras específicas.'),
('acentuacao-grafica', 'Quando acentuar proparoxítonas?', 'Todas são acentuadas.'),
('acentuacao-grafica', 'Qual a regra para acentuar ''saúde''?', 'Hiato com ''i'' ou ''u'' tônico, seguido ou não de ''s''.'),
('acentuacao-grafica', 'Qual a regra para acentuar ''chapéu''?', 'Ditongo aberto ''éu'' em oxítonas.'),
('acentuacao-grafica', 'A palavra ''heroico'' tem acento?', 'Não, ditongos abertos ''ei'' e ''oi'' em paroxítonas não são mais acentuados.'),
('acentuacao-grafica', 'A palavra ''ideia'' tem acento?', 'Não, ditongos abertos ''ei'' em paroxítonas não são mais acentuados.'),
('acentuacao-grafica', 'Quando acentuar monossílabos tônicos?', 'Terminados em A(s), E(s), O(s).'),
('acentuacao-grafica', 'Qual a regra para acentuar verbos ''ter'' e ''vir'' na 3ª pessoa do plural?', 'Têm, vêm (com acento circunflexo).'),
('acentuacao-grafica', 'Quando usar o trema?', 'Não é mais usado após o Acordo Ortográfico de 1990, exceto em nomes próprios.'),
('morfologia-classes', 'O que é um substantivo?', 'Palavra que nomeia seres, objetos, lugares, sentimentos, etc.'),
('morfologia-classes', 'Qual a função de um adjetivo?', 'Caracterizar ou qualificar o substantivo.'),
('morfologia-classes', 'O que é um pronome?', 'Palavra que substitui ou acompanha o substantivo.'),
('morfologia-classes', 'O que é um advérbio?', 'Palavra que modifica um verbo, um adjetivo ou outro advérbio, indicando circunstância.'),
('morfologia-classes', 'Qual a diferença entre preposição e conjunção?', 'Preposição liga palavras; conjunção liga orações ou termos de mesma função.'),
('morfologia-classes', 'O que é um artigo?', 'Palavra que antecede o substantivo, determinando-o ou indeterminando-o.'),
('morfologia-classes', 'O que é um numeral?', 'Palavra que indica quantidade, ordem, fração ou multiplicação.'),
('morfologia-classes', 'O que é um verbo?', 'Palavra que indica ação, estado, fenômeno da natureza.'),
('morfologia-classes', 'O que é uma interjeição?', 'Palavra que exprime emoções, sensações, estados de espírito.'),
('morfologia-classes', 'O que é uma locução adjetiva?', 'Duas ou mais palavras com valor de adjetivo (ex: ''de chuva'' = chuvoso).'),
('morfologia-flexao', 'Como se forma o plural de ''cidadão''?', 'Cidadãos.'),
('morfologia-flexao', 'Qual o feminino de ''cônsul''?', 'Consulesa.'),
('morfologia-flexao', 'O que é um verbo transitivo direto?', 'Verbo que exige complemento sem preposição.'),
('morfologia-flexao', 'O que é um verbo intransitivo?', 'Verbo que não exige complemento.'),
('morfologia-flexao', 'Qual o tempo verbal de ''tinha estudado''?', 'Pretérito mais-que-perfeito composto.'),
('morfologia-flexao', 'Qual o plural de ''pão-de-ló''?', 'Pães-de-ló.'),
('morfologia-flexao', 'Qual o grau superlativo absoluto sintético de ''bom''?', 'Ótimo.'),
('morfologia-flexao', 'Qual o modo verbal que expressa uma ordem ou conselho?', 'Imperativo.'),
('morfologia-flexao', 'O que é um verbo regular?', 'Verbo que mantém o radical e segue as desinências padrão.'),
('morfologia-flexao', 'O que é um verbo irregular?', 'Verbo que sofre alterações no radical ou nas desinências.'),
('sintaxe-termos-essenciais', 'O que é sujeito simples?', 'Apresenta apenas um núcleo.'),
('sintaxe-termos-essenciais', 'O que é sujeito composto?', 'Apresenta dois ou mais núcleos.'),
('sintaxe-termos-essenciais', 'O que é predicado verbal?', 'Tem como núcleo um verbo de ação.'),
('sintaxe-termos-essenciais', 'O que é predicado nominal?', 'Tem como núcleo um nome (substantivo ou adjetivo) e um verbo de ligação.'),
('sintaxe-termos-essenciais', 'O que é sujeito oculto (elíptico)?', 'Não expresso, mas identificável pela desinência verbal.'),
('sintaxe-termos-essenciais', 'O que é sujeito indeterminado?', 'Não se pode ou não se quer identificar o sujeito.'),
('sintaxe-termos-essenciais', 'O que é oração sem sujeito?', 'Oração com verbos impessoais (fenômenos da natureza, haver no sentido de existir).'),
('sintaxe-termos-essenciais', 'Exemplo de predicado verbo-nominal.', 'Os alunos saíram felizes.'),
('sintaxe-termos-essenciais', 'O que é um verbo de ligação?', 'Verbo que liga o sujeito a uma característica (estado).'),
('sintaxe-termos-essenciais', 'Exemplo de verbo de ligação.', 'Ser, estar, parecer, permanecer, ficar, continuar, andar.'),
('sintaxe-termos-integrantes', 'O que é objeto direto?', 'Complemento verbal sem preposição.'),
('sintaxe-termos-integrantes', 'O que é objeto indireto?', 'Complemento verbal com preposição.'),
('sintaxe-termos-integrantes', 'O que é complemento nominal?', 'Termo que completa o sentido de um nome (substantivo, adjetivo, advérbio).'),
('sintaxe-termos-integrantes', 'O que é agente da passiva?', 'Termo que pratica a ação em voz passiva.'),
('sintaxe-termos-integrantes', 'Qual a diferença entre objeto direto e indireto?', 'Direto não tem preposição, indireto tem.'),
('sintaxe-termos-integrantes', 'O que é predicativo do sujeito?', 'Característica atribuída ao sujeito por meio de um verbo de ligação.'),
('sintaxe-termos-integrantes', 'O que é predicativo do objeto?', 'Característica atribuída ao objeto.'),
('sintaxe-termos-integrantes', 'O que é um complemento verbal?', 'Termo que completa o sentido de um verbo transitivo.'),
('sintaxe-termos-integrantes', 'O que é um complemento nominal?', 'Termo que completa o sentido de um nome (substantivo, adjetivo, advérbio).'),
('sintaxe-termos-integrantes', 'Exemplo de objeto direto.', 'Comprei um livro.'),
('sintaxe-termos-acessorios', 'O que é adjunto adnominal?', 'Termo que acompanha o substantivo, caracterizando-o.'),
('sintaxe-termos-acessorios', 'O que é adjunto adverbial?', 'Termo que indica uma circunstância (tempo, lugar, modo, etc.).'),
('sintaxe-termos-acessorios', 'O que é aposto?', 'Termo que explica ou resume outro termo da oração.'),
('sintaxe-termos-acessorios', 'O que é vocativo?', 'Termo que serve para chamar ou interpelar o interlocutor.'),
('sintaxe-termos-acessorios', 'Qual a diferença entre adjunto adnominal e complemento nominal?', 'Adjunto adnominal tem valor ativo, complemento nominal tem valor passivo.'),
('sintaxe-termos-acessorios', 'Exemplo de adjunto adnominal.', 'A casa *velha*.'),
('sintaxe-termos-acessorios', 'Exemplo de adjunto adverbial de tempo.', 'Chegou *ontem*.'),
('sintaxe-termos-acessorios', 'Exemplo de aposto explicativo.', 'Machado de Assis, *o bruxo do Cosme Velho*, foi um grande escritor.'),
('sintaxe-termos-acessorios', 'Exemplo de vocativo.', '*Maria*, venha aqui!'),
('sintaxe-termos-acessorios', 'O que é um termo acessório?', 'Termo que pode ser retirado da oração sem prejuízo de sentido.'),
('sintaxe-periodo-composto', 'O que é uma oração coordenada assindética?', 'Oração coordenada sem conjunção.'),
('sintaxe-periodo-composto', 'O que é uma oração subordinada substantiva?', 'Exerce função de substantivo (sujeito, objeto, etc.).'),
('sintaxe-periodo-composto', 'O que é uma oração subordinada adjetiva?', 'Exerce função de adjetivo, caracterizando um termo da oração principal.'),
('sintaxe-periodo-composto', 'O que é uma oração subordinada adverbial?', 'Exerce função de advérbio, indicando uma circunstância.'),
('sintaxe-periodo-composto', 'Exemplo de oração coordenada aditiva.', 'Ele estuda *e* trabalha.'),
('sintaxe-periodo-composto', 'Exemplo de oração subordinada substantiva subjetiva.', 'É necessário *que você estude*.'),
('sintaxe-periodo-composto', 'Exemplo de oração subordinada adjetiva restritiva.', 'Os alunos *que estudam* passam.'),
('sintaxe-periodo-composto', 'Exemplo de oração subordinada adverbial temporal.', '*Quando chegou*, todos aplaudiram.'),
('sintaxe-periodo-composto', 'O que é um período simples?', 'Período com apenas uma oração.'),
('sintaxe-periodo-composto', 'O que é um período composto?', 'Período com duas ou mais orações.'),
('concordancia', 'Qual a regra geral de concordância verbal?', 'O verbo concorda em número e pessoa com o sujeito.'),
('concordancia', 'Qual a regra geral de concordância nominal?', 'O adjetivo concorda em gênero e número com o substantivo a que se refere.'),
('concordancia', 'Concordância de ''faz'' em ''Faz anos que não o vejo''.', 'Verbo ''fazer'' indicando tempo decorrido é impessoal (sem sujeito), fica no singular.'),
('concordancia', 'Concordância de ''haver'' no sentido de ''existir''.', 'É impessoal, fica no singular (Há muitos problemas).'),
('concordancia', 'Concordância de ''meio'' (advérbio).', 'Invariável (Ela está *meio* cansada).'),
('concordancia', 'Concordância de ''anexo'', ''incluso'', ''obrigado''.', 'Concordam com o substantivo (As fotos *anexas*, A nota *inclusa*, Ela disse *obrigada*).'),
('concordancia', 'Concordância com sujeito composto posposto.', 'O verbo pode concordar com o mais próximo ou com todos (Entraram o pai e a mãe / Entrou o pai e a mãe).'),
('concordancia', 'Concordância com ''um dos que''.', 'O verbo pode ir para o singular ou plural (Ele foi um dos que *passou* / *passaram*).'),
('concordancia', 'Concordância com ''mais de um''.', 'O verbo fica no singular (Mais de um aluno *faltou*).'),
('concordancia', 'Concordância com ''qual de nós''.', 'O verbo concorda com ''qual'' (singular) ou com o pronome pessoal (Qual de nós *fará* / *faremos*).'),
('regencia', 'Qual a regência do verbo ''assistir'' no sentido de ''ver''?', 'Verbo transitivo indireto, exige preposição ''a''.'),
('regencia', 'Qual a regência do verbo ''implicar'' no sentido de ''acarretar''?', 'Verbo transitivo direto, não exige preposição.'),
('regencia', 'Qual a regência do nome ''acesso''?', 'Exige preposição ''a'' (acesso a algo).'),
('regencia', 'Regência do verbo ''obedecer''.', 'Transitivo indireto, exige preposição ''a'' (obedecer *a* algo/alguém).'),
('regencia', 'Regência do verbo ''aspirar'' no sentido de ''desejar''.', 'Transitivo indireto, exige preposição ''a'' (aspirar *a* um cargo).'),
('regencia', 'Regência do verbo ''esquecer'' e ''lembrar'' (pronominal).', 'Com pronome, exigem preposição ''de'' (Esqueceu-se *de* algo).'),
('regencia', 'Regência do verbo ''preferir''.', 'Transitivo direto e indireto, não admite ''do que'' (Prefiro café *a* chá).'),
('regencia', 'Regência do nome ''necessidade''.', 'Exige preposição ''de'' (necessidade *de* algo).'),
('regencia', 'Regência do verbo ''visar'' no sentido de ''ter em vista''.', 'Transitivo indireto, exige preposição ''a'' (Visava *a* um futuro melhor).'),
('regencia', 'Regência do verbo ''agradar'' no sentido de ''contentar''.', 'Transitivo indireto, exige preposição ''a'' (Agradou *ao* público).'),
('crase', 'Quando ocorre a crase?', 'Fusão da preposição ''a'' com o artigo feminino ''a(s)'' ou com pronomes demonstrativos ''a'', ''aquilo'', ''aquela''.'),
('crase', 'Em que caso a crase é proibida antes de palavra masculina?', 'Sempre, a menos que haja uma locução adverbial feminina subentendida (ex: ''à moda de'').'),
('crase', 'A crase é facultativa antes de pronomes possessivos femininos?', 'Sim, antes de ''minha'', ''sua'', ''nossa'', etc.'),
('crase', 'A crase é proibida antes de verbos?', 'Sim, sempre.'),
('crase', 'A crase é proibida antes de numeral cardinal?', 'Sim, exceto se indicar horas.'),
('crase', 'Quando usar crase em ''à noite''?', 'Em locuções adverbiais femininas de tempo, modo, lugar.'),
('crase', 'Qual a regra para crase com nomes de lugar?', 'Se ''volto da'', tem crase; se ''volto de'', não tem crase.'),
('crase', 'A crase é proibida antes de pronomes de tratamento?', 'Sim, exceto ''senhora'', ''senhorita'', ''dona''.'),
('crase', 'Qual a função do acento grave?', 'Indicar a ocorrência da crase.'),
('crase', 'Exemplo de crase obrigatória.', 'Fui *à* feira.'),
('colocacao-pronominal', 'O que é próclise?', 'Pronome oblíquo átono antes do verbo.'),
('colocacao-pronominal', 'O que é ênclise?', 'Pronome oblíquo átono depois do verbo.'),
('colocacao-pronominal', 'O que é mesóclise?', 'Pronome oblíquo átono no meio do verbo (futuro do presente/pretérito).'),
('colocacao-pronominal', 'Qual fator atrai a próclise em ''Não se fala nisso''?', 'Palavra negativa (''não'').'),
('colocacao-pronominal', 'Qual fator atrai a próclise em ''Que Deus o abençoe!''?', 'Pronome interrogativo ou exclamativo.'),
('colocacao-pronominal', 'Quando usar ênclise?', 'Início de frase, verbo no imperativo afirmativo, gerúndio sem preposição.'),
('colocacao-pronominal', 'Quando usar mesóclise?', 'Verbo no futuro do presente ou futuro do pretérito, sem fator de próclise.'),
('colocacao-pronominal', 'Exemplo de próclise.', 'Ele *me* disse.'),
('colocacao-pronominal', 'Exemplo de ênclise.', 'Diga-*me* a verdade.'),
('colocacao-pronominal', 'Exemplo de mesóclise.', 'Far-*lhe*-ei um favor.'),
('semantica-estilistica', 'O que é sinonímia?', 'Relação entre palavras de sentido semelhante.'),
('semantica-estilistica', 'O que é polissemia?', 'Uma palavra com múltiplos significados.'),
('semantica-estilistica', 'O que é metáfora?', 'Comparação implícita, sem conectivo.'),
('semantica-estilistica', 'O que é eufemismo?', 'Suavização de uma ideia desagradável.'),
('semantica-estilistica', 'O que é ironia?', 'Dizer o contrário do que se pensa, com intenção de crítica ou humor.'),
('semantica-estilistica', 'O que é ambiguidade?', 'Duplo sentido em uma frase ou palavra.'),
('semantica-estilistica', 'O que é hipérbole?', 'Exagero intencional para expressar uma ideia.'),
('semantica-estilistica', 'O que é personificação (prosopopeia)?', 'Atribuir características humanas a seres inanimados ou animais.'),
('semantica-estilistica', 'O que é metonímia?', 'Substituição de um termo por outro com o qual tem relação de sentido.'),
('semantica-estilistica', 'O que é pleonasmo?', 'Repetição desnecessária de uma ideia.')
ON CONFLICT DO NOTHING;
